//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportes_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cargamento()
        {
            this.Cargamentos_Productos = new HashSet<Cargamentos_Productos>();
        }
    
        public int ID_Cargamento { get; set; }
        public double Peso { get; set; }
        public Nullable<double> alto { get; set; }
        public Nullable<double> ancho { get; set; }
        public Nullable<double> profundidad { get; set; }
        public int Ruta_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargamentos_Productos> Cargamentos_Productos { get; set; }
        public virtual Rutas Rutas { get; set; }
    }
}
