//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportes_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargamentos_Productos
    {
        public int ID_CP { get; set; }
        public int Producto_ID { get; set; }
        public int Cargamento_ID { get; set; }
    
        public virtual Cargamento Cargamento { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
