//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transportes_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rutas()
        {
            this.Cargamento = new HashSet<Cargamento>();
        }
    
        public int ID_ruta { get; set; }
        public double distancia { get; set; }
        public System.DateTime fecha_salida { get; set; }
        public Nullable<System.TimeSpan> hora_salida { get; set; }
        public System.DateTime fecha_llegadaestimada { get; set; }
        public Nullable<System.DateTime> fecha_llegada { get; set; }
        public Nullable<System.TimeSpan> hora_llegada { get; set; }
        public Nullable<int> tiempo_viaje { get; set; }
        public Nullable<int> Camion_ID { get; set; }
        public Nullable<int> direccion_origen_id { get; set; }
        public Nullable<int> direccion_destino_id { get; set; }
    
        public virtual Camiones Camiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargamento> Cargamento { get; set; }
        public virtual Direcciones Direcciones { get; set; }
        public virtual Direcciones Direcciones1 { get; set; }
    }
}
